[package]
name = "ferrous-dns-infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ferrous-dns-domain.workspace = true
ferrous-dns-application.workspace = true
tokio.workspace = true
async-trait.workspace = true
sqlx.workspace = true
hickory-resolver.workspace = true
hickory-server.workspace = true
hickory-proto.workspace = true
serde.workspace = true
tracing.workspace = true
